<a href="https://colab.research.google.com/github/Pravallikavyas/n/blob/main/Copy_of_Numpy_tasks.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# Numpy



#### 1. Import the numpy package under the name `np` (★☆☆) 
(**hint**: import … as …)

In [ ]:
import numpy as np

#### 2. Print the numpy version and the configuration (★☆☆) 
(**hint**: np.\_\_version\_\_, np.show\_config)

In [ ]:
import numpy as np
np.__version__
np.show_config( )

blas_mkl_info:
  NOT AVAILABLE
blis_info:
  NOT AVAILABLE
openblas_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
blas_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_mkl_info:
  NOT AVAILABLE
openblas_lapack_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
lapack_opt_info:
    libraries = ['openblas', 'openblas']
    library_dirs = ['/usr/local/lib']
    language = c
    define_macros = [('HAVE_CBLAS', None)]
    runtime_library_dirs = ['/usr/local/lib']
Supported SIMD extensions in this NumPy install:
    baseline = SSE,SSE2,SSE3
    found = SSSE3,SSE4

#### 3. Create a null vector of size 10 (★☆☆) 
(**hint**: np.zeros)

In [ ]:
np.zeros(10,dtype=int)

array([0, 0, 0, 0, 0, 0, 0, 0, 0, 0])

#### 4.  How to find the memory size of any array (★☆☆) 
(**hint**: size, itemsize)

In [ ]:
x=np.array([8,9,10])
print(x.size)
print(x.itemsize)
print(x.size*x.itemsize)

3
8
24


#### 5.  How to get the documentation of the numpy add function from the command line? (★☆☆) 
(**hint**: np.info)

In [1]:
import numpy as np
np.info(np.add)

add(x1, x2, /, out=None, *, where=True, casting='same_kind', order='K', dtype=None, subok=True[, signature, extobj])

Add arguments element-wise.

Parameters
----------
x1, x2 : array_like
    The arrays to be added.
    If ``x1.shape != x2.shape``, they must be broadcastable to a common
    shape (which becomes the shape of the output).
out : ndarray, None, or tuple of ndarray and None, optional
    A location into which the result is stored. If provided, it must have
    a shape that the inputs broadcast to. If not provided or None,
    a freshly-allocated array is returned. A tuple (possible only as a
    keyword argument) must have length equal to the number of outputs.
where : array_like, optional
    This condition is broadcast over the input. At locations where the
    condition is True, the `out` array will be set to the ufunc result.
    Elsewhere, the `out` array will retain its original value.
    Note that if an uninitialized `out` array is created via the default
    ``out

#### 6.  Create a null vector of size 10 but the fifth value which is 1 (★☆☆) 
(**hint**: array\[4\])

In [ ]:
x=np.zeros(10,dtype=int)
x[4]=1
print(x)

[0 0 0 0 1 0 0 0 0 0]


#### 7.  Create a vector with values ranging from 10 to 49 (★☆☆) 
(**hint**: np.arange)

In [ ]:
v=np.arange(10,49,5)

#### 8.  Reverse a vector (first element becomes last) (★☆☆) 
(**hint**: array\[::-1\])

In [ ]:
v=np.arange(10,49,3)
v[::-1]

array([46, 43, 40, 37, 34, 31, 28, 25, 22, 19, 16, 13, 10])

#### 9.  Create a 3x3 matrix with values ranging from 0 to 8 (★☆☆) 
(**hint**: reshape)

In [ ]:
a=np.arange(0,9).reshape(3,3)
a

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

#### 10. Find indices of non-zero elements from \[1,2,0,0,4,0\] (★☆☆) 
(**hint**: np.nonzero)

In [ ]:
a=[1,2,0,0,4,0]
b=np.array(a)
c=np.nonzero(b)
c


(array([0, 1, 4]),)

#### 11. Create a 3x3 identity matrix (★☆☆) 
(**hint**: np.eye)

In [ ]:
np.eye(3,dtype=int)

array([[1, 0, 0],
       [0, 1, 0],
       [0, 0, 1]])

#### 12. Create a 3x3x3 array with random values (★☆☆) 
(**hint**: np.random.random)

In [ ]:
x=np.random.random((3,3,3))
x

array([[[0.87105741, 0.35711799, 0.19801268],
        [0.10371415, 0.71182703, 0.91755694],
        [0.91092514, 0.78654761, 0.08971425]],

       [[0.19435055, 0.51850404, 0.40567899],
        [0.5926255 , 0.77553791, 0.85915338],
        [0.53411966, 0.12509692, 0.96956173]],

       [[0.61100082, 0.20072062, 0.31937581],
        [0.53587384, 0.90807013, 0.1120237 ],
        [0.2452779 , 0.81221623, 0.98307058]]])

#### 13. Create a 10x10 array with random values and find the minimum and maximum values (★☆☆) 
(**hint**: min, max)

In [ ]:
x=np.random.random((10,10))
print(x)
y=x.min( )
z=x.max( )
print(y)
print(z)


[[0.31352547 0.76920507 0.01770841 0.36571051 0.66439566 0.31102938
  0.2959665  0.16968966 0.44001575 0.80886542]
 [0.25968825 0.64688295 0.67546506 0.41871657 0.90402608 0.55544392
  0.80331655 0.89910753 0.3544658  0.59700104]
 [0.72635117 0.95460974 0.59287949 0.55613952 0.38263844 0.92012209
  0.79306819 0.12223525 0.67027469 0.3854936 ]
 [0.80471596 0.4696729  0.6713903  0.03595078 0.31660892 0.97576491
  0.86993636 0.51102443 0.82363185 0.86201259]
 [0.75478618 0.36723504 0.86832446 0.83835488 0.89666132 0.02718505
  0.89846935 0.97063369 0.76335539 0.83499933]
 [0.60793392 0.55468205 0.51664362 0.54146649 0.11170108 0.02463407
  0.34492525 0.56387909 0.73403043 0.64844044]
 [0.65122231 0.24262204 0.60064037 0.25078109 0.60300489 0.05649675
  0.38077697 0.67200454 0.85270186 0.40168542]
 [0.08241068 0.3192342  0.28124519 0.07816814 0.98849471 0.93765469
  0.53280312 0.96316699 0.72340967 0.97052409]
 [0.21664057 0.45569696 0.10823859 0.32651247 0.51904766 0.72214527
  0.52903086

#### 14. Create a random vector of size 30 and find the mean value (★☆☆) 
(**hint**: mean)

In [ ]:
import numpy as np
x=np.random.randint(1,500,size=(30))
print(x)
a=np.mean(x)
print(a)

[454 290 347 222  70 181  63 370 459 379 456 168 200 413 185 262 269 432
 283 275 228  33 457 492 491   2 246 106 457 180]
282.3333333333333


#### 15. Create a 2d array with 1 on the border and 0 inside (★☆☆) 
(**hint**: array\[1:-1, 1:-1\])

In [ ]:
x=np.ones((5,5),dtype=int)
x[1:-1,1:-1]=0
print(x)

[[1 1 1 1 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 0 0 0 1]
 [1 1 1 1 1]]


#### 16. How to add a border (filled with 0's) around an existing array? (★☆☆) 
(**hint**: np.pad)

In [ ]:
b=np.pad(x,pad_width=1,mode='constant',constant_values=0)
print(b)

[[0 0 0 0 0 0 0]
 [0 1 1 1 1 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 0 0 0 1 0]
 [0 1 1 1 1 1 0]
 [0 0 0 0 0 0 0]]


#### 17. What is the result of the following expression? (★☆☆) 
(**hint**: NaN = not a number, inf = infinity)

```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1
```

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
0.3 == 3 * 0.1

False

#### 18. Create a 5x5 matrix with values 1,2,3,4 just below the diagonal (★☆☆) 
(**hint**: np.diag)

In [ ]:
X= np.diag(1+np.arange(4),k=-1)
print(X)

[[0 0 0 0 0]
 [1 0 0 0 0]
 [0 2 0 0 0]
 [0 0 3 0 0]
 [0 0 0 4 0]]


#### 19. Create a 8x8 matrix and fill it with a checkerboard pattern (★☆☆) 
(**hint**: array\[::2\])

In [ ]:
c=np.zeros((8,8),dtype=int)
c[1::2,::2]=1
c[::2,1::2]=1
c

array([[0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0],
       [0, 1, 0, 1, 0, 1, 0, 1],
       [1, 0, 1, 0, 1, 0, 1, 0]])

#### 20. Consider a (6,7,8) shape array, what is the index (x,y,z) of the 100th element? 
(**hint**: np.unravel_index)

In [ ]:

print(np.unravel_index(100,(6,7,8)))

(1, 5, 4)


#### 21. Create a checkerboard 8x8 matrix using the tile function (★☆☆) 
(**hint**: np.tile)

In [ ]:

Z = np.tile( np.array([[0,1],[1,0]]), (4,4))
print(Z)

[[0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]
 [0 1 0 1 0 1 0 1]
 [1 0 1 0 1 0 1 0]]


#### 22. Normalize a 5x5 random matrix (★☆☆) 
(**hint**: (x - min) / (max - min))

In [ ]:
import numpy as np
a=np.random.rand(5,5)
print(a)
m1=np.min(a)
m2=np.max(a)
b=(a-m1)/(m2-m1)
print(b)

[[4.94689102e-01 5.16449508e-01 1.14436561e-01 6.74689388e-01
  9.75347156e-01]
 [4.21238163e-01 4.01961733e-01 5.81074693e-01 8.37765816e-04
  5.51315105e-02]
 [3.62166719e-01 8.87342707e-02 6.98245814e-01 4.71936242e-01
  1.17506020e-01]
 [9.45369996e-01 6.91589137e-01 5.80792307e-01 4.43232387e-01
  2.88173915e-01]
 [3.87244411e-01 8.18812357e-01 8.38745703e-01 5.07751300e-01
  9.46557053e-01]]
[[0.50676919 0.52909879 0.11657024 0.69147781 1.        ]
 [0.43139697 0.41161632 0.5954144  0.         0.05571393]
 [0.37078037 0.09019565 0.71565041 0.48342118 0.11971999]
 [0.96923872 0.70881962 0.59512463 0.4539665  0.29485211]
 [0.39651403 0.83937066 0.85982541 0.52017306 0.97045682]]


#### 23. Create a custom dtype that describes a color as four unsigned bytes (RGBA) (★☆☆) 
(**hint**: np.dtype)

In [ ]:
color = np.dtype([("r", np.ubyte, 1),
                ("g", np.ubyte, 1),
                ("b", np.ubyte, 1),
                 ("a", np.ubyte, 1)])
print(color)

[('r', 'u1'), ('g', 'u1'), ('b', 'u1'), ('a', 'u1')]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:4: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  after removing the cwd from sys.path.


#### 24. Multiply a 5x3 matrix by a 3x2 matrix (real matrix product) (★☆☆) 
(**hint**: np.dot | @)

In [ ]:
import numpy as np
a=np.random.random((5,3))
print(a)
b=np.random.random((3,2))
print(b)
c=np.dot(a,b)
print(c)

[[0.28739424 0.85312895 0.33538265]
 [0.47341338 0.11661457 0.78655121]
 [0.80424979 0.59849153 0.1757238 ]
 [0.89433065 0.33829896 0.18739671]
 [0.58005982 0.50813071 0.22852112]]
[[0.17295664 0.92616333]
 [0.82023007 0.13874917]
 [0.03051244 0.37223273]]
[[0.7597021  0.50938533]
 [0.20153036 0.74741839]
 [0.63536285 0.89331701]
 [0.43788133 0.94499013]
 [0.52408202 0.69279588]]


#### 25. Given a 1D array, negate all elements which are between 3 and 8, in place. (★☆☆) 
(**hint**: >, <=)

In [ ]:
import numpy as np
a=np.random.randint(1,30,size=20)
print(a)
for i in range(20):
  if(3<a[i])&(a[i]<8):
    a[i]*=-1
print(a)    



[25 12 10 16 11 17  9  1  5  7 16 12 13 26 16 22 11 20 21 18]
[25 12 10 16 11 17  9  1 -5 -7 16 12 13 26 16 22 11 20 21 18]


#### 26. What is the output of the following script? (★☆☆) 
(**hint**: np.sum)

```python
# Author: Jake VanderPlas

print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

9
10


#### 27. Consider an integer vector Z, which of these expressions are legal? (★☆☆)

```python
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
Z<Z>Z
```

In [ ]:
Z**Z
2 << Z >> 2
Z <- Z
1j*Z
Z/1/1
z<z>z

False

#### 28. What are the result of the following expressions?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
import numpy as np
a=np.array(0) / np.array(0)
b=np.array(0) // np.array(0)
c=np.array([np.nan]).astype(int).astype(float)
print(a)
print(b)
print(c)

nan
0
[-9.22337204e+18]


#### 29. How to round away from zero a float array ? (★☆☆) 
(**hint**: np.uniform, np.copysign, np.ceil, np.abs)

In [ ]:
Z = np.random.uniform(-10,+10,10)
print(np.copysign(np.ceil(np.abs(Z)), Z))


[ 10.  -5.  -4.  -3.  -4.  10. -10.  -2.   2.   2.]


#### 30. How to find common values between two arrays? (★☆☆) 
(**hint**: np.intersect1d)

In [ ]:
a1=np.array([1,2,3,4,5])
a2=np.array([3,4,6,7])
a3=np.intersect1d(a1,a2)
print(a3)

[3 4]


#### 31. How to ignore all numpy warnings (not recommended)? (★☆☆) 
(**hint**: np.seterr, np.errstate)

In [ ]:
defaults = np.seterr(all="ignore")
Z = np.ones(1) / 0
_ = np.seterr(**defaults)
with np.errstate(all="ignore"):
    np.arange(3) / 0

#### 32. Is the following expressions true? (★☆☆) 
(**hint**: imaginary number)

```python
np.sqrt(-1) == np.emath.sqrt(-1)
```

In [ ]:
np.sqrt(-1) == np.emath.sqrt(-1)

False

#### 33. How to get the dates of yesterday, today and tomorrow? (★☆☆) 
(**hint**: np.datetime64, np.timedelta64)

In [ ]:
today = np.datetime64('today', 'D')
yesterday = np.datetime64('today', 'D')-np.timedelta64(1, 'D')
tomorrow = np.datetime64('today', 'D')+np.timedelta64(1, 'D')
print(today)
print(yesterday)
print(tomorrow)

2022-11-23
2022-11-22
2022-11-24


#### 34. How to get all the dates corresponding to the month of July 2016? (★★☆) 
(**hint**: np.arange(dtype=datetime64\['D'\]))

In [ ]:
print(np.arange('2016-07', '2020-08',dtype='datetime64[D]'))

['2016-07-01' '2016-07-02' '2016-07-03' ... '2020-07-29' '2020-07-30'
 '2020-07-31']


#### 35. How to compute ((A+B)\*(-A/2)) in place (without copy)? (★★☆) 
(**hint**: np.add(out=), np.negative(out=), np.multiply(out=), np.divide(out=))

In [ ]:
A = np.ones(3)*1
B = np.ones(3)*2
np.add(A,B,out=B)
np.divide(A,2,out=A)
np.negative(A,out=A)
np.multiply(A,B,out=A)

array([-1.5, -1.5, -1.5])

#### 36. Extract the integer part of a random array using 5 different methods (★★☆) 
(**hint**: %, np.floor, np.ceil, astype, np.trunc)

In [ ]:
Z = np.random.uniform(0,10,10)
print(Z - Z%1)
print(Z // 1)
print(np.floor(Z))
print(Z.astype(int))
print(np.trunc(Z))

[1. 3. 3. 7. 2. 3. 7. 5. 7. 0.]
[1. 3. 3. 7. 2. 3. 7. 5. 7. 0.]
[1. 3. 3. 7. 2. 3. 7. 5. 7. 0.]
[1 3 3 7 2 3 7 5 7 0]
[1. 3. 3. 7. 2. 3. 7. 5. 7. 0.]


#### 37. Create a 5x5 matrix with row values ranging from 0 to 4 (★★☆) 
(**hint**: np.arange)

In [ ]:
Z = np.zeros((5,5))
Z += np.arange(5)
print(Z)

[[0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]
 [0. 1. 2. 3. 4.]]


#### 38. Consider a generator function that generates 10 integers and use it to build an array (★☆☆) 
(**hint**: np.fromiter)

In [ ]:
def generate():
    for x in range(10):
        yield x
Z = np.fromiter(generate(),dtype=float,count=-1)
print(Z)

[0. 1. 2. 3. 4. 5. 6. 7. 8. 9.]


#### 39. Create a vector of size 10 with values ranging from 0 to 1, both excluded (★★☆) 
(**hint**: np.linspace)

In [ ]:
x = np.linspace(0,1,12,endpoint=True)[1:-1]
print(x)

[0.09090909 0.18181818 0.27272727 0.36363636 0.45454545 0.54545455
 0.63636364 0.72727273 0.81818182 0.90909091]


#### 40. Create a random vector of size 10 and sort it (★★☆) 
(**hint**: sort)

In [ ]:
x=np.random.random(10)
print(x)
x.sort( )
print(x)

[0.51067686 0.46183628 0.35588194 0.75276103 0.39505244 0.51664245
 0.71453547 0.34923689 0.87460645 0.02830013]
[0.02830013 0.34923689 0.35588194 0.39505244 0.46183628 0.51067686
 0.51664245 0.71453547 0.75276103 0.87460645]


#### 41. How to sum a small array faster than np.sum? (★★☆) 
(**hint**: np.add.reduce)

In [ ]:
Z = np.arange(10)
np.add.reduce(Z)

45

#### 42. Consider two random array A and B, check if they are equal (★★☆) 
(**hint**: np.allclose, np.array\_equal)

In [ ]:
x=np.random.randint(0,2,6)
print(x)
y=np.random.randint(0,2,6)
print(y)
equal = np.allclose(x,y)
print(equal)
equal = np.array_equal(x,y)
print(equal)


[1 1 0 0 1 0]
[1 1 1 0 0 1]
False
False


#### 43. Make an array immutable (read-only) (★★☆) 
(**hint**: flags.writeable)

In [ ]:
import numpy as np
x = np.zeros(10)
x.flags.writeable = False


ValueError: ignored

#### 44. Consider a random 10x2 matrix representing cartesian coordinates, convert them to polar coordinates (★★☆) 
(**hint**: np.sqrt, np.arctan2)

In [ ]:
import numpy as np
z= np.random.random((10,2))
x,y = z[:,0], z[:,1]
r = np.sqrt(x**2+y**2)
t = np.arctan2(y,x)
print(r)
print(t)

[0.72157649 0.66399522 1.18953301 0.8368281  0.91967521 0.81923619
 0.71714065 1.1572177  0.74800221 0.70879537]
[1.54808902 0.90882522 0.96692103 0.82861715 0.79821201 1.49270078
 0.30022536 0.9185138  0.95999854 0.41031624]


#### 45. Create random vector of size 10 and replace the maximum value by 0 (★★☆) 
(**hint**: argmax)

In [ ]:
x=np.random.random(10)
print(x)
x[x.argmax()] = 0
print(x)

[0.74272259 0.20324823 0.3952649  0.1992246  0.35929579 0.48184687
 0.90209333 0.60529085 0.08538855 0.23494702]
[0.74272259 0.20324823 0.3952649  0.1992246  0.35929579 0.48184687
 0.         0.60529085 0.08538855 0.23494702]


#### 46. Create a structured array with `x` and `y` coordinates covering the \[0,1\]x\[0,1\] area (★★☆) 
(**hint**: np.meshgrid)

In [ ]:
z = np.zeros((5, 5), [('x', float), ('y', float)])
z['x'], z['y'] = np.meshgrid(np.linspace(0, 1, 5), np.linspace(0, 1, 5))
print(z)


[[(0.  , 0.  ) (0.25, 0.  ) (0.5 , 0.  ) (0.75, 0.  ) (1.  , 0.  )]
 [(0.  , 0.25) (0.25, 0.25) (0.5 , 0.25) (0.75, 0.25) (1.  , 0.25)]
 [(0.  , 0.5 ) (0.25, 0.5 ) (0.5 , 0.5 ) (0.75, 0.5 ) (1.  , 0.5 )]
 [(0.  , 0.75) (0.25, 0.75) (0.5 , 0.75) (0.75, 0.75) (1.  , 0.75)]
 [(0.  , 1.  ) (0.25, 1.  ) (0.5 , 1.  ) (0.75, 1.  ) (1.  , 1.  )]]


####  47. Given two arrays, X and Y, construct the Cauchy matrix C (Cij =1/(xi - yj)) 
(**hint**: np.subtract.outer)

In [ ]:
x = np.random.random((5, 5))
y = np.random.random((5, 5))
c = 1 / np.subtract.outer(x, y)
print(c)

[[[[ 3.57337801e+00  1.18139902e+00  2.43335468e+00  1.66974488e+00
     6.08477394e+00]
   [ 1.51469477e+00  1.06680381e+00  3.29612797e+00  2.67449489e+01
     1.22575888e+00]
   [ 2.37150681e+00  1.45952216e+00  4.28055032e+00  4.04061219e+00
     1.07725000e+00]
   [ 1.35266352e+00  1.13696484e+00  1.76981431e+00  1.52550671e+00
     1.52512614e+00]
   [ 1.01879715e+01  6.16490578e+00  1.07038512e+00  5.31527728e+00
     1.09054511e+00]]

  [[ 5.10683224e+00  1.31160800e+00  3.05881343e+00  1.94226522e+00
     1.24512067e+01]
   [ 1.73560527e+00  1.17185440e+00  4.55881733e+00 -2.14404078e+01
     1.36651227e+00]
   [ 2.96171954e+00  1.66354859e+00  6.68522129e+00  6.11785028e+00
     1.18447136e+00]
   [ 1.52613271e+00  1.25706544e+00  2.07900257e+00  1.74981571e+00
     1.74931501e+00]
   [ 7.08023514e+01  1.27914305e+01  1.17617719e+00  9.60561295e+00
     1.20056455e+00]]

  [[-3.35635068e+00  3.72211894e+00 -5.99396071e+00  4.73843967e+01
    -2.41869994e+00]
   [ 1.21345785e+

#### 48. Print the minimum and maximum representable value for each numpy scalar type (★★☆) 
(**hint**: np.iinfo, np.finfo, eps)

In [ ]:
for dtype in [np.int8, np.int32, np.int64]:
   print(np.iinfo(dtype).min)
   print(np.iinfo(dtype).max)
for dtype in [np.float32, np.float64]:
   print(np.finfo(dtype).min)
   print(np.finfo(dtype).max)
   print(np.finfo(dtype).eps)

-128
127
-2147483648
2147483647
-9223372036854775808
9223372036854775807
-3.4028235e+38
3.4028235e+38
1.1920929e-07
-1.7976931348623157e+308
1.7976931348623157e+308
2.220446049250313e-16


#### 49. How to print all the values of an array? (★★☆) 
(**hint**: np.set\_printoptions)

In [ ]:
np.set_printoptions(threshold=10)
x = np.zeros((4, 4))
print(x)

[[0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]
 [0. 0. 0. 0.]]


#### 50. How to find the closest value (to a given scalar) in a vector? (★★☆) 
(**hint**: argmin)

In [ ]:
import numpy as np
x = np.arange(100)
print(x)
a = np.random.uniform(0,100)
print(a)
index = (np.abs(x-a)).argmin()
print(x[index])

[ 0  1  2  3  4  5  6  7  8  9 10 11 12 13 14 15 16 17 18 19 20 21 22 23
 24 25 26 27 28 29 30 31 32 33 34 35 36 37 38 39 40 41 42 43 44 45 46 47
 48 49 50 51 52 53 54 55 56 57 58 59 60 61 62 63 64 65 66 67 68 69 70 71
 72 73 74 75 76 77 78 79 80 81 82 83 84 85 86 87 88 89 90 91 92 93 94 95
 96 97 98 99]
17.88600443517907
18


#### 51. Create a structured array representing a position (x,y) and a color (r,g,b) (★★☆) 
(**hint**: dtype)

In [ ]:
Z = np.zeros(10, [ ('position', [ ('x', float, 1),
                                  ('y', float, 1)]),
                   ('color',    [ ('r', float, 1),
                                  ('g', float, 1),
                                  ('b', float, 1)])])
print(Z)

[((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))
 ((0., 0.), (0., 0., 0.)) ((0., 0.), (0., 0., 0.))]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:5: FutureWarning: Passing (type, 1) or '1type' as a synonym of type is deprecated; in a future version of numpy, it will be understood as (type, (1,)) / '(1,)type'.
  """


#### 52. Consider a random vector with shape (100,2) representing coordinates, find point by point distances (★★☆) 
(**hint**: np.atleast\_2d, T, np.sqrt)

In [ ]:
Z = np.random.random((10,2))
X,Y = np.atleast_2d(Z[:,0], Z[:,1])
D = np.sqrt( (X-X.T)**2 + (Y-Y.T)**2)
print(D)

[[0.         0.45206286 0.58904137 0.32999699 0.51322    0.19911112
  0.72262791 0.59481546 0.56465376 0.5116069 ]
 [0.45206286 0.         0.26805763 0.66066561 0.22425607 0.64992531
  0.31411008 0.73517953 0.67922794 0.27550302]
 [0.58904137 0.26805763 0.         0.66806734 0.07582555 0.76302602
  0.17363892 0.99240647 0.93843132 0.10043442]
 [0.32999699 0.66066561 0.66806734 0.         0.60289188 0.2805673
  0.83684532 0.90849911 0.88503019 0.56845007]
 [0.51322    0.22425607 0.07582555 0.60289188 0.         0.68796326
  0.23399898 0.93034107 0.87761992 0.05898406]
 [0.19911112 0.64992531 0.76302602 0.2805673  0.68796326 0.
  0.90842176 0.65795157 0.64450878 0.67604301]
 [0.72262791 0.31411008 0.17363892 0.83684532 0.23399898 0.90842176
  0.         1.04228323 0.98486018 0.273374  ]
 [0.59481546 0.73517953 0.99240647 0.90849911 0.93034107 0.65795157
  1.04228323 0.         0.05951689 0.96194272]
 [0.56465376 0.67922794 0.93843132 0.88503019 0.87761992 0.64450878
  0.98486018 0.059516

#### 53. How to convert a float (32 bits) array into an integer (32 bits) in place? 
(**hint**: astype(copy=False))

In [ ]:
Z = (np.random.rand(10)*100).astype(np.float32)
Y = Z.view(np.int32)
Y[:] = Z
print(Y)

[34 70 44 12 88  7 88 77 10 82]


#### 54. How to read the following file? (★★☆) 
(**hint**: np.genfromtxt)

```
1, 2, 3, 4, 5
6,  ,  , 7, 8
 ,  , 9,10,11
```

In [ ]:
from io import StringIO
s = StringIO('''1, 2, 3, 4, 5
                6,  ,  , 7, 8
                 ,  , 9,10,11
''')
Z = np.genfromtxt(s, delimiter=",", dtype=int)
print(Z)

[[ 1  2  3  4  5]
 [ 6 -1 -1  7  8]
 [-1 -1  9 10 11]]


#### 55. What is the equivalent of enumerate for numpy arrays? (★★☆) 
(**hint**: np.ndenumerate, np.ndindex)

In [ ]:
Z = np.arange(9).reshape(3,3)
for index, value in np.ndenumerate(Z):
    print(index, value)
for index in np.ndindex(Z.shape):
    print(index, Z[index])

(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8
(0, 0) 0
(0, 1) 1
(0, 2) 2
(1, 0) 3
(1, 1) 4
(1, 2) 5
(2, 0) 6
(2, 1) 7
(2, 2) 8


#### 56. Generate a generic 2D Gaussian-like array (★★☆) 
(**hint**: np.meshgrid, np.exp)

In [ ]:
X, Y = np.meshgrid(np.linspace(-1,1,10), np.linspace(-1,1,10))
D = np.sqrt(X*X+Y*Y)
sigma, mu = 1.0, 0.0
G = np.exp(-( (D-mu)**2 / ( 2.0 * sigma**2 ) ) )
print(G)

[[0.36787944 0.44822088 0.51979489 0.57375342 0.60279818 0.60279818
  0.57375342 0.51979489 0.44822088 0.36787944]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0.63331324 0.54610814 0.44822088]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.60279818 0.73444367 0.85172308 0.9401382  0.98773022 0.98773022
  0.9401382  0.85172308 0.73444367 0.60279818]
 [0.57375342 0.69905581 0.81068432 0.89483932 0.9401382  0.9401382
  0.89483932 0.81068432 0.69905581 0.57375342]
 [0.51979489 0.63331324 0.73444367 0.81068432 0.85172308 0.85172308
  0.81068432 0.73444367 0.63331324 0.51979489]
 [0.44822088 0.54610814 0.63331324 0.69905581 0.73444367 0.73444367
  0.69905581 0

#### 57. How to randomly place p elements in a 2D array? (★★☆) 
(**hint**: np.put, np.random.choice)

In [ ]:
n = 10
p = 3
Z = np.zeros((n,n))
np.put(Z, np.random.choice(range(n*n), p, replace=False),1)
print(Z)

[[0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]
 [1. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 0. 0. 0.]
 [0. 0. 0. 0. 0. 0. 0. 1. 0. 0.]]


#### 58. Subtract the mean of each row of a matrix (★★☆) 
(**hint**: mean(axis=,keepdims=))

In [ ]:
X = np.random.rand(5, 10)
Y = X - X.mean(axis=1, keepdims=True)
print(Y)


[[-0.29123139  0.2308868   0.26780786  0.11164547 -0.40264406 -0.42290225
  -0.09323575  0.02989363  0.2347393   0.33504038]
 [ 0.24830109 -0.00709239 -0.47637115  0.16168332  0.2675612  -0.37358025
   0.10465465  0.0178274  -0.17214442  0.22916056]
 [ 0.34495807  0.10186888  0.27567063  0.10635153 -0.2656856  -0.43530757
  -0.19008991 -0.22089488  0.41130769 -0.12817885]
 [ 0.31412995  0.29121328 -0.10823546 -0.46022866  0.18569495  0.33273454
  -0.51612076  0.33241355 -0.04525571 -0.32634567]
 [ 0.25624125  0.08558687 -0.35618584 -0.32054112 -0.27321558 -0.09010383
   0.29812967  0.45099521 -0.35533187  0.30442524]]


#### 59. How to sort an array by the nth column? (★★☆) 
(**hint**: argsort)

In [ ]:
Z = np.random.randint(0,10,(3,3))
print(Z)
print(Z[Z[:,1].argsort()])

[[7 1 0]
 [0 9 2]
 [0 4 6]]
[[7 1 0]
 [0 4 6]
 [0 9 2]]


#### 60. How to tell if a given 2D array has null columns? (★★☆) 
(**hint**: any, ~)

In [ ]:
import numpy as np
nums = np.random.randint(0,3,(4,10))
print(nums)
print((~nums.any(axis=0)).any())

[[0 1 2 1 1 1 1 0 2 1]
 [1 0 2 2 0 0 2 1 1 1]
 [1 0 1 0 2 1 2 1 0 2]
 [1 2 2 0 1 1 2 0 0 2]]
False


#### 61. Find the nearest value from a given value in an array (★★☆) 
(**hint**: np.abs, argmin, flat)

In [ ]:
Z = np.random.uniform(0,1,10)
z = 0.5
m = Z.flat[np.abs(Z - z).argmin()]
print(m)

0.5833267031455606


#### 62. Considering two arrays with shape (1,3) and (3,1), how to compute their sum using an iterator? (★★☆) 
(**hint**: np.nditer)

In [ ]:
A = np.arange(3).reshape(3,1)
B = np.arange(3).reshape(1,3)
it = np.nditer([A,B,None])
for x,y,z in it: z[...] = x + y
print(it.operands[2])

[[0 1 2]
 [1 2 3]
 [2 3 4]]


#### 63. Create an array class that has a name attribute (★★☆) 
(**hint**: class method)

In [ ]:
class NamedArray(np.ndarray):
    def __new__(cls, array, name="no name"):
        obj = np.asarray(array).view(cls)
        obj.name = name
        return obj
    def __array_finalize__(self, obj):
        if obj is None: return
        self.name = getattr(obj, 'name', "no name")
Z = NamedArray(np.arange(10), "range_10")
print (Z.name)

range_10


#### 64. Consider a given vector, how to add 1 to each element indexed by a second vector (be careful with repeated indices)? (★★★) 
(**hint**: np.bincount | np.add.at)

In [ ]:
Z = np.ones(10)
I = np.random.randint(0,len(Z),20)
Z += np.bincount(I, minlength=len(Z))
print(Z)
# Another solution
np.add.at(Z, I, 1)
print(Z)

[4. 2. 3. 2. 2. 6. 4. 2. 3. 2.]
[ 7.  3.  5.  3.  3. 11.  7.  3.  5.  3.]


#### 65. How to accumulate elements of a vector (X) to an array (F) based on an index list (I)? (★★★) 
(**hint**: np.bincount)

In [ ]:
X = [1,2,3,4,5,6]
I = [1,3,9,3,4,1]
F = np.bincount(I,X)
print(F)

[0. 7. 0. 6. 5. 0. 0. 0. 0. 3.]


#### 66. Considering a (w,h,3) image of (dtype=ubyte), compute the number of unique colors (★★★) 
(**hint**: np.unique)

In [ ]:
w, h = 256, 256
I = np.random.randint(0, 4, (h, w, 3)).astype(np.ubyte)
colors = np.unique(I.reshape(-1, 3), axis=0)
n = len(colors)
print(n)

64


#### 67. Considering a four dimensions array, how to get sum over the last two axis at once? (★★★) 
(**hint**: sum(axis=(-2,-1)))

In [ ]:
A = np.random.randint(0,10,(3,4,3,4))
sum = A.sum(axis=(-2,-1))
print(sum)
sum = A.reshape(A.shape[:-2] + (-1,)).sum(axis=-1)
print(sum)

[[52 59 55 64]
 [48 55 74 56]
 [59 75 50 55]]
[[52 59 55 64]
 [48 55 74 56]
 [59 75 50 55]]


#### 68. Considering a one-dimensional vector D, how to compute means of subsets of D using a vector S of same size describing subset  indices? (★★★) 
(**hint**: np.bincount)

In [ ]:
D = np.random.uniform(0,1,100)
S = np.random.randint(0,10,100)
D_sums = np.bincount(S, weights=D)
D_counts = np.bincount(S)
D_means = D_sums / D_counts
print(D_means)

[0.54580272 0.61451377 0.36141923 0.5683555  0.46841158 0.62017966
 0.57291992 0.57973366 0.52181657 0.43309836]


#### 69. How to get the diagonal of a dot product? (★★★) 
(**hint**: np.diag)

In [ ]:
A = np.random.uniform(0,1,(5,5))
B = np.random.uniform(0,1,(5,5))
np.diag(np.dot(A, B))

array([2.15519477, 0.97885211, 1.09709476, 1.36270771, 1.55128518])

#### 70. Consider the vector \[1, 2, 3, 4, 5\], how to build a new vector with 3 consecutive zeros interleaved between each value? (★★★) 
(**hint**: array\[::4\])

In [ ]:
import numpy as np
Z = np.array([1,2,3,4,5],dtype=int)
nz = 3
Z0 = np.zeros(len(Z) + (len(Z)-1)*(nz))
Z0[::nz+1] = Z
print(Z0)

[1. 0. 0. 0. 2. 0. 0. 0. 3. 0. 0. 0. 4. 0. 0. 0. 5.]


#### 71. Consider an array of dimension (5,5,3), how to mulitply it by an array with dimensions (5,5)? (★★★) 
(**hint**: array\[:, :, None\])

In [ ]:
import numpy as np
nums1 = np.ones((5,5,3))
nums2 = 3*np.ones((5,5))
print(nums1)
new_array = nums1 * nums2[:,:,None]
print(new_array)

[[[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]

 [[1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]
  [1. 1. 1.]]]
[[[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]

 [[3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]
  [3. 3. 3.]]]


#### 72. How to swap two rows of an array? (★★★) 
(**hint**: array\[\[\]\] = array\[\[\]\])

In [ ]:
import numpy as np
my_array = np.array([[1, 2, 3, 4, 5, 6],
                     [7, 8, 9, 10, 11, 12]])
print(my_array)
my_array[[0, 1]] = my_array[[1, 0]]
print(my_array)


[[ 1  2  3  4  5  6]
 [ 7  8  9 10 11 12]]
[[ 7  8  9 10 11 12]
 [ 1  2  3  4  5  6]]


#### 73. Consider a set of 10 triplets describing 10 triangles (with shared vertices), find the set of unique line segments composing all the  triangles (★★★) 
(**hint**: repeat, np.roll, np.sort, view, np.unique)

In [ ]:
faces = np.random.randint(0,100,(10,3))
F = np.roll(faces.repeat(2,axis=1),-1,axis=1)
F = F.reshape(len(F)*3,2)
F = np.sort(F,axis=1)
G = F.view( dtype=[('p0',F.dtype),('p1',F.dtype)] )
G = np.unique(G)
print(G)

[( 3, 51) ( 3, 87) ( 6, 60) ( 6, 79) ( 8, 10) ( 8, 30) ( 9,  9) ( 9, 52)
 (10, 30) (26, 42) (26, 70) (40, 50) (40, 70) (40, 81) (40, 92) (42, 70)
 (50, 78) (50, 82) (50, 92) (51, 87) (53, 53) (53, 70) (60, 79) (70, 81)
 (76, 80) (76, 96) (78, 82) (80, 96)]


#### 74. Given an array C that is a bincount, how to produce an array A such that np.bincount(A) == C? (★★★) 
(**hint**: np.repeat)

In [ ]:
C = np.bincount([1,1,2,3,4,4,6])
A = np.repeat(np.arange(len(C)), C)
print(A)

[1 1 2 3 4 4 6]


#### 75. How to compute averages using a sliding window over an array? (★★★) 
(**hint**: np.cumsum)

In [ ]:
def moving_average(a, n=3) :
    ret = np.cumsum(a, dtype=float)
    ret[n:] = ret[n:] - ret[:-n]
    return ret[n - 1:] / n
Z = np.arange(20)
print(moving_average(Z, n=3))


[ 1.  2.  3.  4.  5.  6.  7.  8.  9. 10. 11. 12. 13. 14. 15. 16. 17. 18.]


#### 76. Consider a one-dimensional array Z, build a two-dimensional array whose first row is (Z\[0\],Z\[1\],Z\[2\]) and each subsequent row is  shifted by 1 (last row should be (Z\[-3\],Z\[-2\],Z\[-1\]) (★★★) 
(**hint**: from numpy.lib import stride_tricks)

In [ ]:
from numpy.lib import stride_tricks

def rolling(a, window):
    shape = (a.size - window + 1, window)
    strides = (a.itemsize, a.itemsize)
    return stride_tricks.as_strided(a, shape=shape, strides=strides)

Z = rolling(np.arange(10), 3)
print(Z)

[[0 1 2]
 [1 2 3]
 [2 3 4]
 [3 4 5]
 [4 5 6]
 [5 6 7]
 [6 7 8]
 [7 8 9]]


#### 77. How to negate a boolean, or to change the sign of a float inplace? (★★★) 
(**hint**: np.logical_not, np.negative)

In [ ]:
Z = np.random.randint(0,2,100)
np.logical_not(Z, out=Z)
Z = np.random.uniform(-1.0,1.0,100)
np.negative(Z, out=Z)

array([-0.02799508,  0.2152954 ,  0.79027607,  0.34158886,  0.09718958,
       -0.58091019, -0.38211492,  0.88589566,  0.40025725, -0.99769692,
        0.78793362,  0.10857867,  0.96876368,  0.42287256, -0.12398455,
        0.42785397, -0.81804515, -0.26101939, -0.80847135, -0.7368692 ,
       -0.49190946, -0.41387834,  0.7285404 , -0.85184388,  0.08410037,
       -0.05515258,  0.84536493, -0.28526398,  0.40489749,  0.74088061,
       -0.07891811,  0.9348585 , -0.07410674,  0.97714385, -0.98621726,
       -0.63435188, -0.33258681, -0.53972075, -0.46860108, -0.42950108,
        0.26785323,  0.88658344, -0.86231014,  0.9241223 ,  0.96284587,
       -0.44380816, -0.83298281, -0.14696443,  0.7600806 , -0.56272503,
        0.84913134,  0.52552967,  0.54987769,  0.84323903, -0.50997881,
        0.94139515, -0.32204664, -0.61258793,  0.02984906, -0.07701492,
        0.39284289,  0.90535641, -0.91797227,  0.77332273, -0.24994837,
       -0.81180204, -0.69835498,  0.69376312,  0.42121379, -0.29

#### 78. Consider 2 sets of points P0,P1 describing lines (2d) and a point p, how to compute distance from p to each line i  (P0\[i\],P1\[i\])? (★★★)

In [ ]:
def distance(P0, P1, p):
    T = P1 - P0
    L = (T**2).sum(axis=1)
    U = -((P0[:,0]-p[...,0])*T[:,0] + (P0[:,1]-p[...,1])*T[:,1]) / L
    U = U.reshape(len(U),1)
    D = P0 + U*T - p
    return np.sqrt((D**2).sum(axis=1))
P0 = np.random.uniform(-10,10,(10,2))
P1 = np.random.uniform(-10,10,(10,2))
p  = np.random.uniform(-10,10,( 1,2))
print(distance(P0, P1, p))

[2.9819159  0.86460647 5.63836959 7.21523189 0.54880074 7.18538969
 3.87727161 2.30162594 3.06651206 8.05256915]


#### 79. Consider 2 sets of points P0,P1 describing lines (2d) and a set of points P, how to compute distance from each point j (P\[j\]) to each line i (P0\[i\],P1\[i\])? (★★★)

In [ ]:
P0 = np.random.uniform(-10, 10, (10,2))
P1 = np.random.uniform(-10,10,(10,2))
p = np.random.uniform(-10, 10, (10,2))
print(np.array([distance(P0,P1,p_i) for p_i in p]))

[[7.44703699e+00 1.53889619e+00 1.72808278e-01 3.09572528e+00
  2.47875170e+00 2.08324197e+00 1.43347005e+01 7.61056408e+00
  4.07916462e+00 1.14286180e+01]
 [2.43981046e+00 7.70903370e+00 1.25327192e+01 4.33024878e+00
  1.02138057e+01 5.25378464e+00 7.46513861e+00 8.63210655e-04
  1.32122661e+01 3.30023845e+00]
 [9.25866524e-01 2.54262797e+00 3.66539469e+00 6.46792619e+00
  1.41484737e+00 3.34098184e+00 7.21884769e+00 5.66337234e-01
  1.86540113e+00 4.45902032e+00]
 [1.45531430e+00 6.74067611e+00 3.55808918e+00 1.04464980e+01
  1.34901292e+00 7.81811859e+00 3.76188721e+00 2.67851115e+00
  1.67939236e+00 1.37985604e+00]
 [1.18969604e+00 1.28174518e+01 7.70516295e-02 1.66433091e+01
  2.23940424e+00 1.33532644e+01 2.07201093e+00 3.94254868e+00
  7.89853539e+00 4.31959429e-01]
 [6.96537121e+00 1.88397950e+00 1.35288089e+01 1.04623854e+00
  1.12718175e+01 1.26966430e+00 1.57791390e+00 5.63113263e+00
  8.65162424e+00 2.12696877e+00]
 [6.47500178e-01 4.51710866e+00 4.03993285e+00 8.28571735e

#### 80. Consider an arbitrary array, write a function that extract a subpart with a fixed shape and centered on a given element (pad with a `fill` value when necessary) (★★★) 
(**hint**: minimum, maximum)

In [ ]:
Z = np.random.randint(0,10,(10,10))
shape = (5,5)
fill  = 0
position = (1,1)

R = np.ones(shape, dtype=Z.dtype)*fill
P  = np.array(list(position)).astype(int)
Rs = np.array(list(R.shape)).astype(int)
Zs = np.array(list(Z.shape)).astype(int)

R_start = np.zeros((len(shape),)).astype(int)
R_stop  = np.array(list(shape)).astype(int)
Z_start = (P-Rs//2)
Z_stop  = (P+Rs//2)+Rs%2

R_start = (R_start - np.minimum(Z_start,0)).tolist()
Z_start = (np.maximum(Z_start,0)).tolist()
R_stop = np.maximum(R_start, (R_stop - np.maximum(Z_stop-Zs,0))).tolist()
Z_stop = (np.minimum(Z_stop,Zs)).tolist()

r = [slice(start,stop) for start,stop in zip(R_start,R_stop)]
z = [slice(start,stop) for start,stop in zip(Z_start,Z_stop)]
R[r] = Z[z]
print(Z)
print(R)

[[7 2 7 7 4 4 5 5 5 9]
 [8 1 5 0 4 3 4 4 1 7]
 [7 3 6 7 2 1 1 7 7 6]
 [5 7 5 0 8 0 1 5 9 5]
 [1 6 0 1 9 6 6 8 1 8]
 [7 0 5 3 8 4 8 2 7 7]
 [4 3 7 6 1 2 4 9 4 2]
 [6 3 6 8 8 1 5 8 7 8]
 [6 2 4 8 0 8 8 6 7 8]
 [0 2 8 9 4 3 6 2 8 0]]
[[0 0 0 0 0]
 [0 7 2 7 7]
 [0 8 1 5 0]
 [0 7 3 6 7]
 [0 5 7 5 0]]


/usr/local/lib/python3.7/dist-packages/ipykernel_launcher.py:23: FutureWarning: Using a non-tuple sequence for multidimensional indexing is deprecated; use `arr[tuple(seq)]` instead of `arr[seq]`. In the future this will be interpreted as an array index, `arr[np.array(seq)]`, which will result either in an error or a different result.


#### 81. Consider an array Z = \[1,2,3,4,5,6,7,8,9,10,11,12,13,14\], how to generate an array R = \[\[1,2,3,4\], \[2,3,4,5\], \[3,4,5,6\], ..., \[11,12,13,14\]\]? (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [6]:
import numpy as np
Z = np.arange(1, 15, dtype=np.uint32)
print(np.lib.stride_tricks.sliding_window_view(Z, window_shape=4))

[[ 1  2  3  4]
 [ 2  3  4  5]
 [ 3  4  5  6]
 [ 4  5  6  7]
 [ 5  6  7  8]
 [ 6  7  8  9]
 [ 7  8  9 10]
 [ 8  9 10 11]
 [ 9 10 11 12]
 [10 11 12 13]
 [11 12 13 14]]


#### 82. Compute a matrix rank (★★★) 
(**hint**: np.linalg.svd) (suggestion: np.linalg.svd)

In [ ]:
import numpy as np
my_matrix = np.array([[1, 2, 1], [3, 4, 7], [3, 6, 3]])
print("Matrix")
for row in my_matrix:
    print(row)
rank = np.linalg.matrix_rank(my_matrix)
print("Rank of the given Matrix is : ",rank)

Matrix
[1 2 1]
[3 4 7]
[3 6 3]
Rank of the given Matrix is :  2


#### 83. How to find the most frequent value in an array? 
(**hint**: np.bincount, argmax)

In [ ]:
import numpy as np
x = np.array([1,2,3,4,5,1,2,1,1,1])
print("Original array:")
print(x)
print("Most frequent value in the above array:")
print(np.bincount(x).argmax())

Original array:
[1 2 3 4 5 1 2 1 1 1]
Most frequent value in the above array:
1


#### 84. Extract all the contiguous 3x3 blocks from a random 10x10 matrix (★★★) 
(**hint**: stride\_tricks.as\_strided)

In [ ]:
import numpy as np
arra1 = np.random.randint(0,5,(10,10))
print("Original arrays:")
print(arra1)
n = 3
i = 1 + (arra1.shape[0]-3)
j = 1 + (arra1.shape[1]-3)
result = np.lib.stride_tricks.as_strided(arra1, shape=(i, j, n, n), strides = arra1.strides + arra1.strides)
print("\nContiguous 3x3 blocks:")
print(result)

Original arrays:
[[2 4 4 4 3 0 3 3 3 2]
 [1 2 0 0 3 2 2 3 0 3]
 [4 1 2 4 4 4 2 1 0 0]
 [0 3 1 1 4 2 4 4 2 0]
 [2 1 2 1 0 0 4 2 0 0]
 [3 1 2 3 2 1 4 4 2 4]
 [2 2 2 2 4 3 3 1 1 1]
 [2 1 2 4 0 1 0 0 4 3]
 [0 4 4 2 2 2 1 0 3 1]
 [1 2 2 3 3 1 0 4 2 1]]

Contiguous 3x3 blocks:
[[[[2 4 4]
   [1 2 0]
   [4 1 2]]

  [[4 4 4]
   [2 0 0]
   [1 2 4]]

  [[4 4 3]
   [0 0 3]
   [2 4 4]]

  [[4 3 0]
   [0 3 2]
   [4 4 4]]

  [[3 0 3]
   [3 2 2]
   [4 4 2]]

  [[0 3 3]
   [2 2 3]
   [4 2 1]]

  [[3 3 3]
   [2 3 0]
   [2 1 0]]

  [[3 3 2]
   [3 0 3]
   [1 0 0]]]


 [[[1 2 0]
   [4 1 2]
   [0 3 1]]

  [[2 0 0]
   [1 2 4]
   [3 1 1]]

  [[0 0 3]
   [2 4 4]
   [1 1 4]]

  [[0 3 2]
   [4 4 4]
   [1 4 2]]

  [[3 2 2]
   [4 4 2]
   [4 2 4]]

  [[2 2 3]
   [4 2 1]
   [2 4 4]]

  [[2 3 0]
   [2 1 0]
   [4 4 2]]

  [[3 0 3]
   [1 0 0]
   [4 2 0]]]


 [[[4 1 2]
   [0 3 1]
   [2 1 2]]

  [[1 2 4]
   [3 1 1]
   [1 2 1]]

  [[2 4 4]
   [1 1 4]
   [2 1 0]]

  [[4 4 4]
   [1 4 2]
   [1 0 0]]

  [[4 4 2]
   [4 2 4]
  

#### 85. Create a 2D array subclass such that Z\[i,j\] == Z\[j,i\] (★★★) 
(**hint**: class method)

In [ ]:
class Symetric(np.ndarray):
    def __setitem__(self, index, value):
        i,j = index
        super(Symetric, self).__setitem__((i,j), value)
        super(Symetric, self).__setitem__((j,i), value)

def symetric(Z):
    return np.asarray(Z + Z.T - np.diag(Z.diagonal())).view(Symetric)

S = symetric(np.random.randint(0,10,(5,5)))
S[2,3] = 42
print(S)

[[ 0  6  9 13 13]
 [ 6  9 11  0  8]
 [ 9 11  0 42 10]
 [13  0 42  2 11]
 [13  8 10 11  2]]


#### 86. Consider a set of p matrices wich shape (n,n) and a set of p vectors with shape (n,1). How to compute the sum of of the p matrix products at once? (result has shape (n,1)) (★★★) 
(**hint**: np.tensordot)

In [ ]:
p, n = 10, 20
M = np.ones((p,n,n))
V = np.ones((p,n,1))
S = np.tensordot(M, V, axes=[[0, 2], [0, 1]])
print(S)

[[200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]
 [200.]]


#### 87. Consider a 16x16 array, how to get the block-sum (block size is 4x4)? (★★★) 
(**hint**: np.add.reduceat)

In [ ]:
import numpy as np
arra1 = np.ones((16,16))
k = 4
print("Original arrays:")
print(arra1)
result = np.add.reduceat(np.add.reduceat(arra1, np.arange(0, arra1.shape[0], k), axis=0),
                                      np.arange(0, arra1.shape[1], k), axis=1)
print("\nBlock-sum (4x4) of the said array:")
print(result)

Original arrays:
[[1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]
 [1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1. 1.]]

Block-sum (4x4) of the said array:
[[16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]
 [16. 16. 16. 16.]]


#### 88. How to implement the Game of Life using numpy arrays? (★★★)

In [ ]:
def iterate(Z):
    N = (Z[0:-2,0:-2] + Z[0:-2,1:-1] + Z[0:-2,2:] +
         Z[1:-1,0:-2]                + Z[1:-1,2:] +
         Z[2:  ,0:-2] + Z[2:  ,1:-1] + Z[2:  ,2:])
    birth = (N==3) & (Z[1:-1,1:-1]==0)
    survive = ((N==2) | (N==3)) & (Z[1:-1,1:-1]==1)
    Z[...] = 0
    Z[1:-1,1:-1][birth | survive] = 1
    return Z

Z = np.random.randint(0,2,(50,50))
for i in range(100): Z = iterate(Z)
print(Z)

[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]
[[0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 ...
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]
 [0 0 0 ... 0 0 0]]


#### 89. How to get the n largest values of an array (★★★) 
(**hint**: np.argsort | np.argpartition)

In [ ]:
Z = np.arange(10000)
np.random.shuffle(Z)
n = 5
print (Z[np.argsort(Z)[-n:]])
print (Z[np.argpartition(-Z,n)[:n]])

[9995 9996 9997 9998 9999]
[9995 9998 9997 9999 9996]


#### 90. Given an arbitrary number of vectors, build the cartesian product (every combinations of every item) (★★★) 
(**hint**: np.indices)

In [ ]:
def cartesian(arrays):
    arrays = [np.asarray(a) for a in arrays]
    shape = (len(x) for x in arrays)

    ix = np.indices(shape, dtype=int)
    ix = ix.reshape(len(arrays), -1).T

    for n, arr in enumerate(arrays):
        ix[:, n] = arrays[n][ix[:, n]]

    return ix

print (cartesian(([1, 2, 3], [4, 5], [6, 7])))

[[1 4 6]
 [1 4 7]
 [1 5 6]
 [1 5 7]
 [2 4 6]
 [2 4 7]
 [2 5 6]
 [2 5 7]
 [3 4 6]
 [3 4 7]
 [3 5 6]
 [3 5 7]]


#### 91. How to create a record array from a regular array? (★★★) 
(**hint**: np.core.records.fromarrays)

In [ ]:
Z = np.array([("Hello", 2.5, 3),
              ("World", 3.6, 2)])
R = np.core.records.fromarrays(Z.T,
                               names='col1, col2, col3',
                               formats = 'S8, f8, i8')
print(R)

[(b'Hello', 2.5, 3) (b'World', 3.6, 2)]


#### 92. Consider a large vector Z, compute Z to the power of 3 using 3 different methods (★★★) 
(**hint**: np.power, \*, np.einsum)

In [ ]:
x = np.random.rand(int(5e7))
%timeit np.power(x,3)
%timeit x*x*x
%timeit np.einsum('i,i,i->i',x,x,x)

3.76 s ± 38.9 ms per loop (mean ± std. dev. of 7 runs, 1 loop each)
144 ms ± 680 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)
125 ms ± 729 µs per loop (mean ± std. dev. of 7 runs, 10 loops each)


#### 93. Consider two arrays A and B of shape (8,3) and (2,2). How to find rows of A that contain elements of each row of B regardless of the order of the elements in B? (★★★) 
(**hint**: np.where)

In [ ]:
A = np.random.randint(0,5,(8,3))
B = np.random.randint(0,5,(2,2))
C = (A[..., np.newaxis, np.newaxis] == B)
rows = np.where(C.any((3,1)).all(1))[0]
print(rows)

[2]


#### 94. Considering a 10x3 matrix, extract rows with unequal values (e.g. \[2,2,3\]) (★★★)

In [ ]:
Z = np.random.randint(0,5,(10,3))
print(Z)
E = np.all(Z[:,1:] == Z[:,:-1], axis=1)
U = Z[~E]
print(U)
U = Z[Z.max(axis=1) != Z.min(axis=1),:]
print(U)

[[4 2 3]
 [0 4 0]
 [0 4 2]
 [4 0 0]
 [4 4 4]
 [0 0 4]
 [4 4 4]
 [0 0 0]
 [3 4 1]
 [0 2 1]]
[[4 2 3]
 [0 4 0]
 [0 4 2]
 [4 0 0]
 [0 0 4]
 [3 4 1]
 [0 2 1]]
[[4 2 3]
 [0 4 0]
 [0 4 2]
 [4 0 0]
 [0 0 4]
 [3 4 1]
 [0 2 1]]


#### 95. Convert a vector of ints into a matrix binary representation (★★★) 
(**hint**: np.unpackbits)

In [ ]:
I = np.array([0, 1, 2, 3, 15, 16, 32, 64, 128], dtype=np.uint8)
print(np.unpackbits(I[:, np.newaxis], axis=1))

[[0 0 0 0 0 0 0 0]
 [0 0 0 0 0 0 0 1]
 [0 0 0 0 0 0 1 0]
 [0 0 0 0 0 0 1 1]
 [0 0 0 0 1 1 1 1]
 [0 0 0 1 0 0 0 0]
 [0 0 1 0 0 0 0 0]
 [0 1 0 0 0 0 0 0]
 [1 0 0 0 0 0 0 0]]


#### 96. Given a two dimensional array, how to extract unique rows? (★★★) 
(**hint**: np.ascontiguousarray)

In [ ]:
Z = np.random.randint(0,2,(6,3))
T = np.ascontiguousarray(Z).view(np.dtype((np.void, Z.dtype.itemsize * Z.shape[1])))
_, idx = np.unique(T, return_index=True)
uZ = Z[idx]
print(uZ)

[[0 0 0]
 [0 0 1]
 [0 1 0]
 [1 0 1]
 [1 1 0]]


#### 97. Considering 2 vectors A & B, write the einsum equivalent of inner, outer, sum, and mul function (★★★) 
(**hint**: np.einsum)

In [ ]:
A = np.random.uniform(0,1,10)
B = np.random.uniform(0,1,10)
np.einsum('i->', A)       
np.einsum('i,i->i', A, B) 
np.einsum('i,i', A, B)    
np.einsum('i,j->ij', A, B)

array([[0.14946847, 0.25443194, 0.08070033, 0.23722059, 0.25882435,
        0.25544384, 0.21042196, 0.23065722, 0.12229106, 0.11692186],
       [0.54148375, 0.92173794, 0.29235541, 0.85938591, 0.93765047,
        0.92540381, 0.76230171, 0.83560858, 0.44302736, 0.42357621],
       [0.12357942, 0.21036243, 0.06672243, 0.19613222, 0.21399405,
        0.21119907, 0.17397531, 0.19070567, 0.10110934, 0.09667012],
       [0.26923626, 0.45830605, 0.1453648 , 0.4273034 , 0.46621807,
        0.46012879, 0.37903125, 0.41548085, 0.22028183, 0.21061034],
       [0.40222259, 0.68468134, 0.21716617, 0.63836528, 0.69650142,
        0.6874044 , 0.56624962, 0.62070311, 0.32908764, 0.31463902],
       [0.42450142, 0.72260538, 0.22919486, 0.6737239 , 0.73508016,
        0.72547927, 0.5976138 , 0.65508343, 0.34731558, 0.33206667],
       [0.08765697, 0.14921363, 0.04732735, 0.1391199 , 0.1517896 ,
        0.14980707, 0.12340363, 0.13527076, 0.07171856, 0.06856975],
       [0.16362256, 0.27852568, 0.0883423

#### 98. Considering a path described by two vectors (X,Y), how to sample it using equidistant samples (★★★)? 
(**hint**: np.cumsum, np.interp)

In [ ]:
phi = np.arange(0, 10*np.pi, 0.1)
a = 1
x = a*phi*np.cos(phi)
y = a*phi*np.sin(phi)
dr = (np.diff(x)**2 + np.diff(y)**2)
r = np.zeros_like(x)
r[1:] = np.cumsum(dr)               
r_int = np.linspace(0, r.max(), 200) 
x_int = np.interp(r_int, r, x)       
y_int = np.interp(r_int, r, y)

#### 99. Given an integer n and a 2D array X, select from X the rows which can be interpreted as draws from a multinomial distribution with n degrees, i.e., the rows which only contain integers and which sum to n. (★★★) 
(**hint**: np.logical\_and.reduce, np.mod)

In [ ]:
X = np.asarray([[1.0, 0.0, 3.0, 8.0],
                [2.0, 0.0, 1.0, 1.0],
                [1.5, 2.5, 1.0, 0.0]])
n = 4
M = np.logical_and.reduce(np.mod(X, 1) == 0, axis=-1)
M &= (X.sum(axis=-1) == n)
print(X[M])

[[2. 0. 1. 1.]]


#### 100. Compute bootstrapped 95% confidence intervals for the mean of a 1D array X (i.e., resample the elements of an array with replacement N times, compute the mean of each sample, and then compute percentiles over the means). (★★★) 
(**hint**: np.percentile)

In [ ]:
X = np.random.randn(100)
N = 1000
idx = np.random.randint(0, X.size, (N, X.size))
means = X[idx].mean(axis=1)
confint = np.percentile(means, [2.5, 97.5])
print(confint)

[-0.23574735  0.14199616]
